apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: video-consumer
  name: video-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-consumer
  template:
    metadata:
      labels:
        app: video-consumer
    spec:
      containers:
      - image: video-consumer:latest
        imagePullPolicy: IfNotPresent
        name: video-consumer
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kafka-broker-service:29092
          - name: KAFKA_TOPIC_NAME
            value: streaming-video-classifier
          - name: MONGODB_CONN_URI
            value: mongodb://mongodb-service:27017